name: ci
on:
  schedule:
    - cron: "0 9 * * 1"
jobs:
  build_x86:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: ${{matrix.build_type}}
    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: python3 -m pip install pyoai
    - name: Get papers
      run: bash code/run.sh
    - name: Push
      run: (git -c user.name='Xiao Wang' -c user.email='no@email.com' commit -am"weekly update" || true )&& git push
